export const tripEntities = [
  {
    id: 1,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
  },
  {
    id: 2,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
  },
  {
    id: 3,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
  },
  {
    id: 4,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
  },
];
