export const tripDummyEntities = [
  {
    id: 1,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
    group: {
      id: 1,
      cargoName: 'Food',
    },
  },
  {
    id: 2,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
    group: {
      id: 1,
      cargoName: 'Food',
    },
  },
  {
    id: 3,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
    group: {
      id: 1,
      cargoName: 'Food',
    },
  },
  {
    id: 4,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
  },
  {
    id: 5,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
    group: {
      id: 2,
      cargoName: 'Chicken',
    },
  },
  {
    id: 6,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
    group: {
      id: 2,
      cargoName: 'Chicken',
    },
  },
  {
    id: 7,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
    group: {
      id: 3,
      cargoName: 'Fruit',
    },
  },
];
