export const fakeTrips = [
  {
    id: 1,
    dayStart: '3.01',
    hourStart: '21:00',
    locationStart: 'Szczecin',
    dayEnd: '4.01',
    hourEnd: '10:30',
    locationEnd: 'Berlin',
    countryStart: 'PL',
    countryEnd: 'DE',
    counterStart: 101458,
    counterEnd: 102010,
    group: {
      id: 1,
      cargoName: 'Food',
    },
  },
  {
    id: 2,
    dayStart: '5.01',
    hourStart: '18:32',
    locationStart: 'Berlin',
    dayEnd: '6.01',
    hourEnd: '12:47',
    locationEnd: 'Vessoul',
    countryStart: 'DE',
    countryEnd: 'FR',
    counterStart: 103628,
    counterEnd: 106710,
    group: {
      id: 1,
      cargoName: 'Food',
    },
  },
  {
    id: 3,
    dayStart: '7.01',
    hourStart: '13:52',
    locationStart: 'Vessoul',
    dayEnd: '9.01',
    hourEnd: '12:47',
    locationEnd: 'Shtokholm',
    countryStart: 'FR',
    countryEnd: 'SA',
    counterStart: 107628,
    counterEnd: 112710,
    group: {
      id: 2,
      cargoName: 'Chicken',
    },
  },
  {
    id: 4,
    dayStart: '7.01',
    hourStart: '13:52',
    locationStart: 'Vessoul',
    dayEnd: '9.01',
    hourEnd: '12:47',
    locationEnd: 'Shtokholm',
    countryStart: 'FR',
    countryEnd: 'SA',
    counterStart: 107628,
    counterEnd: 112710,
    group: {
      id: 2,
      cargoName: 'Chicken',
    },
  },
  {
    id: 5,
    dayStart: '7.01',
    hourStart: '13:52',
    locationStart: 'Vessoul',
    dayEnd: '9.01',
    hourEnd: '12:47',
    locationEnd: 'Shtokholm',
    countryStart: 'FR',
    countryEnd: 'SA',
    counterStart: 107628,
    counterEnd: 112710,
    group: {
      id: 2,
      cargoName: 'Chicken',
    },
  },
  {
    id: 6,
    dayStart: '7.01',
    hourStart: '13:52',
    locationStart: 'Vessoul',
    dayEnd: '9.01',
    hourEnd: '12:47',
    locationEnd: 'Shtokholm',
    countryStart: 'FR',
    countryEnd: 'SA',
    counterStart: 107628,
    counterEnd: 112710,
    group: null,
  },
  {
    id: 7,
    dayStart: '7.01',
    hourStart: '13:52',
    locationStart: 'Vessoul',
    dayEnd: '9.01',
    hourEnd: '12:47',
    locationEnd: 'Shtokholm',
    countryStart: 'FR',
    countryEnd: 'SA',
    counterStart: 107628,
    counterEnd: 112710,
    group: null,
  },
  {
    id: 8,
    dayStart: '7.01',
    hourStart: '13:52',
    locationStart: 'Vessoul',
    dayEnd: '9.01',
    hourEnd: '12:47',
    locationEnd: 'Shtokholm',
    countryStart: 'FR',
    countryEnd: 'SA',
    counterStart: 107628,
    counterEnd: 112710,
    group: null,
  },
];
