services:
  postgres-card:
    container_name: ptd-lite-db
    image: postgres:alpine3.16
    environment:
      POSTGRES_DB: card-db-v2
      POSTGRES_USER: mateuszuran
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - ./card-db-v2:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped