pdf:
  csv:
    link: https://res.cloudinary.com/dzwnsabwr/raw/upload/v1687112220/user_metadata_i2zrt4.csv

frontend:
  url: http://localhost:5173

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/card-db-v2
    driver-class-name: org.postgresql.Driver
    username: mateuszuran
    password: password

  security:
    oauth2:
      resourceserver:
        jwt:
          audience: https://ptd-lite/api
          issuer-uri: https://dev-t6j70c45sd0mgjac.eu.auth0.com/