pdf:
  csv:
    link: ${CSV_LINK}
hour-rate:
  json:
    link: ${JSON_LINK}

frontend:
  urls: http://localhost:5173,http://localhost:5173/home
backend:
  url: http://localhost:8080

# Machine to Machine credentials #
ptd:
  lite:
    machine-to-machine:
      domain: ${M2M_DOMAIN}
      audience: ${M2M_AUDIENCE}
      client-secret: ${M2M_CLIENT_SECRET}
      client-id: ${M2M_CLIENT_ID}

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/card-db
    driver-class-name: org.postgresql.Driver
    username: mateuszuran
    password: password

  security:
    oauth2:
      resourceserver:
        jwt:
          audience: ${AUTH0_AUDIENCE}
          issuer-uri: ${AUTH0_ISSUER_URI}

  application:
    name: ptd-lite

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true