pdf:
  csv:
    link: https://res.cloudinary.com/dzwnsabwr/raw/upload/v1718383956/user_metadata_witcnu.csv
hour-rate:
  json:
    link: https://res.cloudinary.com/dzwnsabwr/raw/upload/v1689863848/driver_rates_json_tshfmc.txt

frontend:
  urls: http://localhost:5173,http://localhost:5173/home
backend:
  url: http://localhost:8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/card-db
    driver-class-name: org.postgresql.Driver
    username: mateuszuran
    password: password

  application:
    name: ptd-lite

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health","prometheus", "metrics" ]
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

application:
  cors:
    origins: http://localhost:5173